stages:
  - 单元测试

单元测试:
  stage: 单元测试
  image: registry.cn-hangzhou.aliyuncs.com/xialintai/phpnginx
  cache:
      paths:
        - vendor
  script:
    - date
    - composer config -g repo.packagist composer https://packagist.phpcomposer.com
    - date
    - composer up
    - date
    - phpunit --bootstrap vendor/autoload.php tests/LdapTest.php
    - date
    - git remote set-url origin  git@github.com:xltxlm/ldap.git
    - git push --all
    - date
  only:
    - master
  tags:
    - latest